import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";
import Nav from "react-bootstrap/Nav";
import Button from "react-bootstrap/Button";

import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

// TODO: FIX THIS 'const Home: NextPage' to about page
const about: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NAVBAR */}
      <Navbar
        className="navbar"
        collapseOnSelect
        expand="lg"
        bg="dark"
        variant="dark"
      >
        <Container>
          <Navbar.Brand href="/">NFT COLLECTION 1 TITLE</Navbar.Brand>
          <Navbar.Toggle aria-controls="responsive-navbar-nav" />
          <Navbar.Collapse id="responsive-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link href="#">ABOUT</Nav.Link>
              <Nav.Link href="/rarityCollection">RARITY/COLLECTION</Nav.Link>
              <Nav.Link href="/roadmap">ROADMAP</Nav.Link>
            </Nav>
            <Nav>
              <Button
                className={styles.connectBtn}
                variant="primary outline-success"
                id="connect-btn"
              >
                CONNECT WALLET
              </Button>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>

      {/* MAIN */}
      <main className={styles.about}>
        <Container>
          <Row>
            <Col id="leftAboutCol" className={styles.leftAboutCol} xs={4}>
              <h1 className={styles.wrapper}> Got cancelled?</h1>
              <p className={styles.wrapper}>
                {" "}
                Here, we will insert some sort of catchy phrase. But, now, we
                don't have any phrase, so we just wanted to fill this area in
                with plenty of text. I hope you have a stellar day!
              </p>
            </Col>

            <Col className={styles.rightAboutCol} xs={8}>
              <h1
                id="home-container-right-column-h1"
                className={styles.centerHorizontal}
              >
                NFT TITLE HERE
              </h1>
            </Col>
          </Row>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default about;